apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "discount-calculator"
  description: "Car Discount Calculation Service"
  tags:
    - backend
    - data-layer
    - flogo
  tibcoPlatformApps:
    - appType: Flogo
      appName: Discount Calculator
      dataPlaneName: Platform-Demo-EKS (Development)
      dpId: cuico3vctghk7irje3a0
      capabilityInstanceId: cv2qreukokbud8rqrpn0
      appId: cv2s90lviu18b0t91l50
    - appType: BWCE
      appName: Discount Calculator
      dataPlaneName: Platform-Demo-EKS (Production)
      dpId: cuico3vctghk7irje3a0
      capabilityInstanceId: cv2qreukokbud8rqrpn0
      appId: cv2s90lviu18b0t91l50
  links:
    - title: TIBCO Cloud Home
      url: https://cloud.tibco.com/
    - title: Documentation
      url: https://eu.integration.cloud.tibco.com/docs/index.html
    - title: TIBCO Cloud Integration
      url: https://eu.integration.cloud.tibco.com/applications
    - title: VSCode Editor (File)
      url: vscode://file/Users/hpeters/VSCodeFolders/tibco-next-flogo-demo/flogo-app-discount-calculator.json
    - title: VSCode Editor (Folder)
      url: vscode://file/Users/hpeters/VSCodeFolders/tibco-next-flogo-demo/
# https://tibcoats.us-west.my.tibco.com/cp/flogo/appdetails/endpoints?dp_id=cuico3vctghk7irje3a0&capability_instance_id=cv2qreukokbud8rqrpn0&app_id=cv2s90lviu18b0t91l50
  annotations:
    github.com/project-slug: TIBCO-Hub-Backstage/tibco-next-demo
    backstage.io/techdocs-ref: dir:.
#    backstage.io/kubernetes-id: bwce-ah-test-1
#    jenkins.io/job-full-name: Build_BWCE_EAR_DB
spec:
  type: service
  lifecycle: production
  system: car-order-system
  owner: finance-department
  providesApis: [ "car-discount-api" ]
  consumesApis:
    - car-details-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "car-discount-api"
  description: "An API that provides car discounts"
  tags:
    - finance
    - rest
  links:
    - url: https://github.com/TIBCO-Hub-Backstage/tibco-next-demo
      title: GitHub Repo
      icon: github
    - url: https://github.com/TIBCO-Hub-Backstage/tibco-next-demo/blob/master/sample-api.json
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: finance-department
  apiConsumedBy: [ "component:car-order-ui"]
  definition:
    $text: ./sample-api.json
