apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "bwce-db-adapter"
  description: "Database Adapter"
  tags:
    - backend
    - data-layer
    - bwce
    - adapter
    - platform
# https://tibcoats.us-west.my.tibco.com/cp/bwce/appdetails/processes?dp_id=cuico3vctghk7irje3a0&capability_instance_id=cv3bc6mkokbud8rqrpu0&app_id=cvdc8o5viu18b0t91md0
  tibcoPlatformApps:
    - appType: BWCE
      appName: Database Adapter
      dataPlaneName: Platform-Demo-EKS (Development)
      dpId: cuico3vctghk7irje3a0
      capabilityInstanceId: cv3bc6mkokbud8rqrpu0
      appId: cvdc8o5viu18b0t91md0
    - appType: BWCE
      appName: Database Adapter
      dataPlaneName: Platform-Demo-EKS (Production)
      dpId: cuico3vctghk7irje3a0
      capabilityInstanceId: cv3bc6mkokbud8rqrpu0
      appId: cvdc8o5viu18b0t91md0
  links:
    - title: TIBCO Business Works
      url: https://www.tibco.com/products/tibco-businessworks
    - title: BWCE Documentation
      url: https://docs.tibco.com/products/tibco-businessworks-container-edition-2-8-1
  annotations:
    github.com/project-slug: TIBCO-Hub-Backstage/github-actions
    backstage.io/techdocs-ref: dir:.
#    backstage.io/kubernetes-id: bwce-ah-test-1
#    jenkins.io/job-full-name: Build_BWCE_EAR_DB
spec:
  type: service
  lifecycle: production
  system: car-order-system
  owner: operational-department
  providesApis: [ "car-details-api" ]
  dependsOn:
    - resource:default/cars-database
    - component:default/discount-calculator
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "car-details-api"
  description: "An API that provides car details"
  tags:
    - store
    - rest
  links:
    - url: https://github.com/TIBCO-Hub-Backstage/tibco-next-demo
      title: GitHub Repo
      icon: github
    - url: https://github.com/TIBCO-Hub-Backstage/tibco-next-demo/blob/master/sample-api.json
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "CarImporter"
  apiConsumedBy: [ "component:discount-calculator","component:car-information-provider"]
  definition:
    $text: ./../sample-api.json
